### ISSUE TITLE
Make mandatory components members of Entity

### ISSUE THREAD

**Issue by Kangz** [DaemonDevelopers/CBSE-Toolchain#22]
Mandatory components are members of all entities so it would make sense to not have to go through the Get to access them (the fact that we want to access them often is probably what made them mandatory anyway). So we should special case them and
* Move them as public members of Entity
* Not have them in the component dependencies part of a component constructor

**Comment by Kangz** [comment]
Actually this will interact badly with inheritance so postpone it for aftr inheritance is implemented.

**Comment by Viech** [comment]
Also it will get even more complex when we realize that any component that the mandatory components depend on is also implicitly mandatory. I would rather not special-case them to much. You still want to be able to `Get` them, you still want to `ForAll` over them, etc. If they and their dependencies are directly accessible *in addition* to all the usual component mechanics that would be an improvment, but please don't make them an entirely different kind of thing, it's not worth the extra performance.

**Comment by Kangz** [comment]
Closing as won't do
