### ISSUE TITLE
"invalid access to non-static data member" warning spam.

### ISSUE THREAD

**Issue by Viech** [DaemonDevelopers/CBSE-Toolchain#27]
For every entity and every component of that entity I get a compiler warning like this:

    CBSEBackend.cpp:1618: warning: invalid access to non-static data member 'BarricadeEntity::c_BarricadeComponent'  of NULL object [-Winvalid-offsetof]
      myoffsetof(BarricadeEntity, c_BarricadeComponent),
                                  ^
    CBSEBackend.cpp:12: in definition of macro 'myoffsetof'
     #define myoffsetof(st, m) static_cast<int>((size_t)(&((st *)0)->m))
                                                                     ^

**Comment by Kangz** [comment]
You can try to replace zero by one and remove one on the final result :P otherwise I'll have to try something more invasive.

**Comment by TimePath** [comment]
How about something like this?

    template<class T, typename U>
    std::ptrdiff_t myoffsetof(U T::*member) {
        return reinterpret_cast<std::ptrdiff_t>(
                &(reinterpret_cast<T*>(nullptr)->*member)
        );
    }

`myoffsetof(&BarricadeEntity::c_BarricadeComponent);`

**Comment by Viech** [comment]
@Kangz ↑

**Comment by Kangz** [comment]
The template thing seems fine to me; I would have to study pointer to members but it would indeed be nicer, do you have a doc on what it is?

**Comment by TimePath** [comment]
It's basically a type safe `offsetof`

`&type::member` creates pointers (which if cast to `int` is the same as `offsetof`)
And `.*` or `->*` applies them much like `operaror[]` works with offsets (indices)

A pointer to a component of entity called c is declared like so: `component entity::*c`

**Comment by TimePath** [comment]
@Kangz I don't think I can make this change unless there's a base `Component` class

**Comment by Kangz** [comment]
you can introduce one :)
